test:
  mode:             "charge" # either charge or discharge mode
  max_test_time:    0.5 # test time in minutes
  max_test_voltage: 5
  min_test_voltage: 0
  max_current:      0
  flow_rate:        0

# parameters for the scan go here
scan:
  filename:         'C:\Temp\Example scan.nc'
  title:            Example scan
  start:            0     # (V)
  stop:             5     # (V)
  step:             0.04  # (V)
  test:             False
  test2:            True
  x_label:          'scan voltage'
  x_units:          'V'
  y_label:          'measured voltage'
  y_units:          'V'
  integration_time: 0.1 # (s)    # This is not implemented
  stabilize_time:   0.001 # (s)
  ao_channel:       2
  ai_channel:       2
  stop_timeout:       3000   # (ms) How much time to give scan loop to stop before forcefully terminating it
  gui_refresh_time:   10     # (ms) How often gui checks if here's new data (usually quicker than time_step)

# set limits for the analog out channels and optionally give them custom display names
ao:
  1:
    name:           Channel 1
    upper_limit:    5.4       # (Volt)
    lower_limit:    -5.4      # (Volt)
  2:
    name:           Channel 2
    upper_limit:    5.4       # (Volt)
    lower_limit:    -5.4      # (Volt)

# set parameters for the monitor here
monitor:
  time_step:        50   # (ms) Note that the basic analog approach doesn't really go faster than 0.010 seconds
  plot_points:      110
  1:
    name:           AI Channel 1
    xlabel:         'time'
  2:
    name:           AI Channel 2
  gui_refresh_time: 10     # (ms) How often gui checks if here's new data (usually quicker than time_step)
  text_update_time: 500      # (ms) Minimum time for the gui to update the value displayed as text
  stop_timeout:     1000      # (ms) How much time to give monitor to stop before forcefully terminating it