# an example of a configuration file
# also used for running the blink operations
#############

user: Your Name Here

whatever_other_parameters_you_like_to_add:  None

# set parameters for the blink instrument here:
blink instrument:
  max_blink_period: 2   # (s)
  min_blink_period: 0.2 # (s)

# Set parameters for the monitor here:
monitor:
  time_step:        0.100   # period with which Operator retrieves data from device
  gui_refresh_time: 0.010   # (s) How often gui checks if here's new data (usually quicker than time_step)
#  stop_timeout:     1      # (s) How much time to give monitor to stop before forcefully terminating it

# Set parameters for the scan here
# This scan measure the state of the device a number of times with a specified interval time
scan:
# filename:             'C:\Temp\test.nc'
  blink_period:         0.6 # (s) blink rate to set the device to
  time_between_points:  0.1 # (s) time between each datapoint
  number_of_points:     40  #     number_of_points * read_period determines the total duration of this scan

